### ISSUE TITLE
dont resolve _home-assistant._tcp.local

### ISSUE THREAD

**Issue by antoniosap** [madpilot/mDNSResolver#10]
i place many debug code in your sources.

I don't know mDNS packet format.
your code give me always 'unresolved'

any idea ? on esp8266

**Comment by madpilot** [comment]
Can you post some source code, so I can see what you are doing?

Better yet, if you can post a wireshark dump of the mDNS requests and responses, that would make debugging possible.

**Comment by madpilot** [comment]
Oh. Wait. _home-assistant._tcp.local is probably not a valid A record. This library doesn't resolve service types - it only resolves names.

Are you on OSX, Linux, or Windows?

**Comment by antoniosap** [comment]
linux ubuntu.
for debug files i begin to prepare

**Comment by madpilot** [comment]
This library lets you find the IP address By the host name that is announced via avahi: ie mymachine.local

It sounds like you want to discover the machine on your network that is running home assistant, that is you want to search by service.

The https://github.com/mrdunk/esp8266_mdns project is probably a better fit for you

**Comment by antoniosap** [comment]
that library have this issue now

**Comment by madpilot** [comment]
Ok, closing this one off. Thanks!
